### ISSUE TITLE
请问一下作者如何查看上传和下载的文件列表

### ISSUE THREAD

**Issue by yyy33** [felixonmars/BaiduPCS-Go#16]
我准备写个脚本批量上传文件,但但是如果遇到上传失败的文件的话我想知道是哪个文件上传失败了

在shell里面运行的话上传成功和上传失败的返回值是一样的吗

**Comment by masx200** [comment]
https://github.com/masx200/baidupcs-batch-upload

**Comment by yyy33** [comment]
> https://github.com/masx200/baidupcs-batch-upload

谢谢。
