### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by oncebeloved** [felixonmars/BaiduPCS-Go#40]
![Screenshot_2021-01-19-12-10-02-632_com termux](https://user-images.githubusercontent.com/51181996/104986929-57fc4980-5a4f-11eb-8ec2-d11bba6da055.jpg)
 mipsle版本下载失败 另外arm64版本下载提示网络超时

**Comment by wang-haoxian** [comment]
这个估计是因为文件过大无法通过web的API下载，如果你在网页版的云盘下载也会报错让你用客户端下载。
