### ISSUE TITLE
x509: certificate is not valid for nb.cache.baidupcs.com

### ISSUE THREAD

**Issue by Rorotaroho** [felixonmars/BaiduPCS-Go#6]
hi, 
我在下载文件的时候遇到了如下的报错：
Get https://nb.cache.baidupcs.com/file/****: x509: certificate is valid for baidu.com, 其他一堆地址, not nb.cache.baidupcs.com
我使用的是locate模式，我尝试了其他模式，不是相同的错误就是下载速度非常慢，我有会员。

不知道你们是否有遇到相同的问题？还请帮忙看下_(:з」∠)_

**Comment by Rorotaroho** [comment]
emmm
自己解决了，关掉htpps支持就行。

**Comment by 451835239** [comment]
怎么关闭？
