### ISSUE TITLE
速度还是不行

### ISSUE THREAD

**Issue by 631068264** [felixonmars/BaiduPCS-Go#8]
![image](https://user-images.githubusercontent.com/8144089/85226703-83f91300-b40b-11ea-8cc8-57de3c578f70.png)

非会员

而且波动很大 0 30 15 70 50  反复横跳

**Comment by pongfcnkl** [comment]
开svip

**Comment by 631068264** [comment]
@pongfcnkl 我用钱开会员的话，我用这个干嘛。。。。。

**Comment by pongfcnkl** [comment]
> 
> 
> @pongfcnkl 我用钱开会员的话，我用这个干嘛。。。。。

不想充钱那就去找代下。。。
